//LOGIN
export const LOGIN_ACCOUNT_REQUEST = "LOGIN_ACCOUNT_REQUEST";
export const LOGIN_ACCOUNT_SUCCESS = "LOGIN_ACCOUNT_SUCCESS";
export const LOGIN_ACCOUNT_FAILED = "LOGIN_ACCOUNT_FAILED";

export const LOGOUT_ACCOUNT_SUCCESS = "LOGOUT_ACCOUNT_SUCCESS";

export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAILED = "SEND_OTP_FAILED";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

// PATIENTS
export const ALL_PATIENT_REQUEST = "ALL_PATIENT_REQUEST";
export const ALL_PATIENT_SUCCESS = "ALL_PATIENT_SUCCESS";
export const ALL_PATIENT_FAILED = "ALL_PATIENT_FAILED";

export const FETCH_PATIENT_REQUEST = "FETCH_PATIENT_REQUEST";
export const FETCH_PATIENT_SUCCESS = "FETCH_PATIENT_SUCCESS";
export const FETCH_PATIENT_FAILED = "FETCH_PATIENT_FAILED";

export const VALID_PATIENT_REQUEST = "VALID_PATIENT_REQUEST";
export const VALID_PATIENT_SUCCESS = "VALID_PATIENT_SUCCESS";
export const VALID_PATIENT_FAILED = "VALID_PATIENT_FAILED";

export const UPDATE_PATIENT_INFO_SUCCESS = "UPDATE_PATIENT_INFO_SUCCESS";

export const LOGIN_PATIENT_REQUEST = "LOGIN_PATIENT_REQUEST";
export const LOGIN_PATIENT_SUCCESS = "LOGIN_PATIENT_SUCCESS";
export const LOGIN_PATIENT_FAILED = "LOGIN_PATIENT_FAILED";

export const LOGOUT_PATIENT_REQUEST = "LOGOUT_PATIENT_REQUEST";
export const LOGOUT_PATIENT_SUCCESS = "LOGOUT_PATIENT_SUCCESS";
export const LOGOUT_PATIENT_FAILED = "LOGOUT_PATIENT_FAILED";


// APPOINTMENT
export const FETCH_APPOINTMENT_REQUEST = "FETCH_APPOINTMENT_REQUEST";
export const FETCH_APPOINTMENT_SUCCESS = "FETCH_APPOINTMENT_SUCCESS";
export const FETCH_APPOINTMENT_FAILED = "FETCH_APPOINTMENT_FAILED";

export const FETCH_DENTIST_APPOINTMENT_SUCCESS = "FETCH_DENTIST_APPOINTMENT_SUCCESS";
export const FETCH_DENTIST_APPOINTMENT_FAILED = "FETCH_DENTIST_APPOINTMENT_FAILED";
export const APPROVED_DENTIST_APPOINTMENT_SUCCESS = "APPROVED_DENTIST_APPOINTMENT_SUCCESS";

export const CREATE_APPOINTMENT_REQUEST = "CREATE_APPOINTMENT_REQUEST";
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";
export const CREATE_APPOINTMENT_FAILED = "CREATE_APPOINTMENT_FAILED";

export const RESPONSE_APPOINTMENT_SUCCESS = "RESPONSE_APPOINTMENT_SUCCESS";

export const UPDATE_APPOINTMENT_SUCCESS = "UPDATE_APPOINTMENT_SUCCESS";
export const APPROVED_APPOINTMENT_SUCCESS = "APPROVED_APPOINTMENT_SUCCESS";

export const DELETE_APPOINTMENT_REQUEST = "DELETE_APPOINTMENT_REQUEST";
export const DELETE_APPOINTMENT_SUCCESS = "DELETE_APPOINTMENT_SUCCESS";
export const DELETE_APPOINTMENT_FAILED = "DELETE_APPOINTMENT_FAILED";

// SERVICES
export const FETCH_SERVICES_REQUEST = "FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAILED = "FETCH_SERVICES_FAILED";

// DENTIST
export const FETCH_DENTIST_REQUEST = "FETCH_DENTIST_REQUEST";
export const FETCH_DENTIST_SUCCESS = "FETCH_DENTIST_SUCCESS";
export const FETCH_DENTIST_FAILED = "FETCH_DENTIST_FAILED";

export const LOGIN_DENTIST_SUCCESS = "LOGIN_DENTIST_SUCCESS";

export const ACTIVE_DENTIST_REQUEST = "ACTIVE_DENTIST_REQUEST";
export const ACTIVE_DENTIST_SUCCESS = "ACTIVE_DENTIST_SUCCESS";

export const UPDATE_DENTIST_INFO_SUCCESS = "UPDATE_DENTIST_INFO_SUCCESS";

export const LOGOUT_DENTIST_SUCCESS = "LOGOUT_DENTIST_SUCCESS";

// ANNOUNCEMENT
export const FETCH_ANNOUNCEMENT_REQUEST = "FETCH_ANNOUNCEMENT_REQUEST";
export const FETCH_ANNOUNCEMENT_SUCCESS = "FETCH_ANNOUNCEMENT_SUCCESS";
export const FETCH_ANNOUNCEMENT_FAILED = "FETCH_ANNOUNCEMENT_FAILED";

// PAYMENT
export const FETCH_PAYMENT_REQUEST = "FETCH_PAYMENT_REQUEST";
export const FETCH_PAYMENT_SUCCESS = "FETCH_PAYMENT_SUCCESS";
export const FETCH_PAYMENT_FAILED = "FETCH_PAYMENT_FAILED";

export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAILED = "CREATE_PAYMENT_FAILED";

export const FETCH_NEW_PAYMENT_SUCCESS = "FETCH_NEW_PAYMENT_SUCCESS";
export const CANCELLED_PAYMENT_SUCCESS = "CANCELLED_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";

// INSTALLMENT
export const FETCH_INSTALLMENT_REQUEST = "FETCH_INSTALLMENT_REQUEST";
export const FETCH_INSTALLMENT_SUCCESS = "FETCH_INSTALLMENT_SUCCESS";
export const FETCH_INSTALLMENT_FAILED = "FETCH_INSTALLMENT_FAILED";

//MESSAGE
export const FETCH_MESSAGE_REQUEST = "FETCH_MESSAGE_REQUEST";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_FAILED = "FETCH_MESSAGE_FAILED";

export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_NEW_MESSAGE_SUCCESS = "CREATE_NEW_MESSAGE_SUCCESS";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const ADMIN_SEND_MESSAGE_SUCCESS = "ADMIN_SEND_MESSAGE_SUCCESS";
export const RESPONSE_MESSAGE_SUCCESS = "RESPONSE_MESSAGE_SUCCESS";

//FEE
export const FETCH_FEE_REQUEST = "FETCH_FEE_REQUEST";
export const FETCH_FEE_SUCCESS = "FETCH_FEE_SUCCESS";
export const FETCH_FEE_FAILED = "FETCH_FEE_FAILED";

export const UPDATE_FEE_SUCCESS = "UPDATE_FEE_SUCCESS";

//TREATMENT
export const CREATE_TREATMENT_SUCCESS = "CREATE_TREATMENT_SUCCESS";

//SCHEDULE
export const FETCH_SCHEDULE_REQUEST = "FETCH_SCHEDULE_REQUEST";
export const FETCH_SCHEDULE_SUCCESS = "FETCH_SCHEDULE_SUCCESS";
export const FETCH_SCHEDULE_FAILED = "FETCH_SCHEDULE_FAILED";

//PRESCRIPTION
export const FETCH_PRESCRIPTION_REQUEST = "FETCH_PRESCRIPTION_REQUEST";
export const FETCH_PRESCRIPTION_SUCCESS = "FETCH_PRESCRIPTION_SUCCESS";
export const FETCH_PRESCRIPTION_FAILED = "FETCH_PRESCRIPTION_FAILED";

export const CREATE_PRESCRIPTION_SUCCESS = "CREATE_PRESCRIPTION_SUCCESS";

// NOTIFICATION
export const FETCH_NOTIFICATION_REQUEST = "FETCH_NOTIFICATION_REQUEST";
export const FETCH_NOTIFICATION_SUCCESS = "FETCH_NOTIFICATION_SUCCESS";
export const FETCH_NOTIFICATION_FAILED = "FETCH_NOTIFICATION_FAILED";

export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS";
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";
export const DELETE_ALL_NOTIFICATION_SUCCESS = "DELETE_ALL_NOTIFICATION_SUCCESS";

//INSURANCE
export const FETCH_INSURANCE_REQUEST = "FETCH_INSURANCE_REQUEST";
export const FETCH_INSURANCE_SUCCESS = "FETCH_INSURANCE_SUCCESS";
export const FETCH_INSURANCE_FAILED = "FETCH_INSURANCE_FAILED";

export const FETCH_ALL_INSURANCE_REQUEST = "FETCH_ALL_INSURANCE_REQUEST";
export const FETCH_ALL_INSURANCE_SUCCESS = "FETCH_ALL_INSURANCE_SUCCESS";
export const FETCH_ALL_INSURANCE_FAILED = "FETCH_ALL_INSURANCE_FAILED";

export const CREATE_INSURANCE_SUCCESS = "CREATE_INSURANCE_SUCCESS";
export const UPDATE_INSURANCE_SUCCESS = "UPDATE_INSURANCE_SUCCESS";
export const DELETE_INSURANCE_SUCCESS = "DELETE_INSURANCE_SUCCESS";

export const FETCH_ADMIN_REQUEST = "FETCH_ADMIN_REQUEST";
export const FETCH_ADMIN_SUCCESS = "FETCH_ADMIN_SUCCESS";
export const FETCH_ADMIN_FAILED = "FETCH_ADMIN_FAILED";